version: "3.3"

networks:
  web_network:
    driver: bridge

services:

  detecter:
    build:
      context: ./app/
      network: host
    container_name: detected_con
    networks: 
      - web_network